stages:
  - build
  - deploy
  - rotate_gpg_keys

variables:
  REGISTRY: registry.ddbuild.io
  BUILDER_IMAGE_REPO: $REGISTRY/486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/jmeter-datadog-backend-listener:latest
  GPG_IMAGE: $REGISTRY/ci/agent-key-management-tools/gpg:1@sha256:a6033e3c52feb3198285732be55068afd87583385f94aafe927c5d1f6c4ddb37

deploy_to_maven_central:
  stage: deploy
  tags: [ "docker-in-docker:amd64" ]
  image: $BUILDER_IMAGE_REPO

  only:
    - tags
  when: manual
  script:
    # Ensure we don't print commands being run to the logs during credential
    # operations
    - set +eux

    - echo "Fetching Sonatype user..."
    - export CENTRAL_USER_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.jmeter-datadog-backend-listener.publishing.central_username_token --with-decryption --query "Parameter.Value" --out text)

    - echo "Fetching Sonatype password..."
    - export CENTRAL_PASS_TOKEN=$(aws ssm get-parameter --region us-east-1 --name ci.jmeter-datadog-backend-listener.publishing.central_password_token --with-decryption --query "Parameter.Value" --out text)

    - echo "Fetching signing key password..."
    - export GPG_PASSPHRASE=$(aws ssm get-parameter --region us-east-1 --name ci.jmeter-datadog-backend-listener.signing.gpg_passphrase --with-decryption --query "Parameter.Value" --out text)

    - echo "Fetching signing key..."
    - GPG_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.jmeter-datadog-backend-listener.signing.gpg_private_key --with-decryption --query "Parameter.Value" --out text)

    - printf -- "$GPG_KEY" | gpg --import --batch

    - echo "Building release..."
    - mvn -DperformRelease=true -DskipTests -Darguments=-DskipTests --settings ./settings.xml clean deploy

    - echo "Cleaning up..."

    # unset the env variables
    - unset CENTRAL_USER_TOKEN
    - unset CENTRAL_PASS_TOKEN
    - unset GPG_PASSPHRASE
    - unset GPG_KEY

    - set -x


verify_gpg_image:
  stage: build
  tags: [ "docker-in-docker:amd64" ]
  image: $GPG_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
  script:
    - test -x /create.sh
    - gpg --version
    - aws --version

verify_builder_image:
  stage: build
  tags: [ "docker-in-docker:amd64" ]
  image: $BUILDER_IMAGE_REPO
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      when: manual
  script:
    - mvn --version
    - gpg --version
    - aws --version

# This job generates the GPG key
# NOTE: This is included for once gpg keys expire, this has not been run before
create_key:
  stage: rotate_gpg_keys
  when: manual

  tags:
    - "docker-in-docker:amd64"

  image: $GPG_IMAGE
  variables:
    PROJECT_NAME: "jmeter-datadog-backend-listener"
    EXPORT_TO_KEYSERVER: "true"
  script:
    - /create.sh
  artifacts:
    expire_in: 13 mos
    paths:
      - ./pubkeys/

# This job makes a new Docker image of maven used for `deploy_to_maven_central` and sends it to $BUILDER_IMAGE_REPO
rebuild_maven_image:
  stage: build
  image: $REGISTRY/docker:18.03.1
  when: manual
  script:
    - docker build --label target=build --tag $BUILDER_IMAGE_REPO .     # Build the Dockerfile from this directory
    - docker push $BUILDER_IMAGE_REPO
  tags: [ "docker-in-docker:amd64" ]
